layout_spectrum: 0.7050904454663396
typography_spectrum: 0.7836818019859493
color:
  brandColors:
    - '#000110'
    - '#DDDEE2'
    - '#D71E3D'
    - '#57A4DA'
    - '#C98024'
  brandStrength: 0.8749121222645044
  lightness: 0.8149108542129397
  saturation: 0.8089088245760649
  rhythmicContrast: 0.6718195602297783
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: FreeMarketHeroes
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Free Market Heroes Podcast
description: Interviews with Heroes of the Free Market
purpose: []
