typography_spectrum: 0.74268
color:
  brandColors:
    - '#000110'
    - '#dddee2'
    - '#d71e3d'
    - '#57a4da'
    - '#c98024'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.26377
analytics:
  google: null
  facebook: null
  twitter: null
name: FreeMarketHeroes
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Free Market Heroes Podcast
description: Interviews with Heroes of the Free Market
purpose: []
