name: FreeMarketHeroes
favicon: null
layout_spectrum: 0.25434
typography_spectrum: 0.74268
title: Free Market Heroes Podcast
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000110'
    - '#dddee2'
    - '#d71e3d'
    - '#57a4da'
    - '#c98024'
  brandStrength: 0.875
  lightness: 0.1875
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
