name: FreeMarketHeroes
favicon: null
layout_spectrum: 0.25434
typography_spectrum: 0.74268
title: Free Market Heroes Podcast
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#b8dbdc'
    - '#35527c'
    - '#fe0000'
    - '#7a7a7a'
  brandStrength: 0.875
  lightness: 0.1875
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
