name: FreeMarketHeroes
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74268
title: Free Market Heroes Podcast
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: Free Market Heroes Entrepreneur Politics Podcast
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#b8dbdc'
    - '#35527c'
    - '#fe0000'
    - '#7a7a7a'
  brandStrength: 0.875
  lightness: 0.6875
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
