name: FreeMarketHeroes
favicon: null
layout_spectrum: 1
typography_spectrum: 0.06444701761938632
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5
  lightness: 0.17050705756992102
  saturation: 0.7118965249974281
  rhythmicContrast: 0.2955525170546025
purpose: []
